name: CI/CD Backend Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/sistema-despachos-ventas:latest .

      - name: Publicar imagen en ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/sistema-despachos-ventas:latest
